name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git checkout main
      - run: git checkout ${{ github.event.pull_request.head.sha }}
      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      # Install Poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      # Install dependencies via Poetry
      - name: Install dependencies
        run: poetry install
      # Run Django tests
      - name: Run Django test
        run: poetry run python manage.py test
      # Pylint test
      - name: Git Pylint Github Action
        uses: vcoder4c/git_pylint@master
        env:
          DEFAULT_TARGET_BRANCH: main